version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=sluch_music
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
